import React, { useRef } from "react"
import { useState } from "react"
import { IoMdSearch } from "react-icons/io"
import axios from "axios"
import "../components/search.css"


const api_url = import.meta.env.VITE_API_URL;
const PortScan = () => {
  const [value, setValue] = useState();
  const [trace, setTrace] = useState(true);
  const [data, setData] = useState({
    host: "192.111.168...",
    port: 21,
    status: "Open",
    service: "FTP – Auth brute force, Anonymous Login",
  });
  const [msg, setMsg] = useState("");

  const refer = useRef(null);

  const cancel_req = async () => {
    // console.log("hit cancel request")
    try {
      setTrace(true);
      await axios.post(`${api_url}/cancel`);
    } catch (error) {
      console.log("My error ", error);
      return;
    }
  };

  const sendRequest = async () => {
    if (!value || value.trim() == "") return;
    setTrace(false);
    setData("");
    setMsg("");
    refer.current.style.display = "block";
    try {
      const result = await axios.get(
        `${api_url}/port?ip=${value}`
      );
      // console.log("only ",result.response.data);
      // console.log(result.data.data);
      // refer.current.style.display = "none";
      refer.current.style.display = "none";
      setTrace(true);
      setData(result.data.data);
    } catch (error) {
      refer.current.style.display = "none";
      // console.log(error.response.data);
      setTrace(true);
      setMsg(error.response.data.data.msg);
 
    }
  };

  return (
    <div
      style={{ marginTop: "20px" }}
      className="w-full flex justify-center items-center flex-col"
    >
      <div className="flex justify-center items-center flex-col w-[70vw]">
        <h1 className="font-bold">Important Warning</h1>
        <span>
          This tool is intended strictly for educational and authorized security
          testing purposes only. You may use it only on systems, servers,{" "}
        </span>
        <span>
          or networks you own or on those for which you have explicit written
          permission to test.
        </span>
        <span>
          The results generated by this tool are approximately 90% accurate and not guaranteed to be 100% precise. In some cases, the tool may produce false positives or false negatives. Accuracy and detection logic will be improved and refined through future updates.
        </span>
      </div>
      <div className="w-full flex justify-center items-center mt-5 flex-col gap-4">
        <div className="w-full flex justify-center items-center gap-4">
          <input
            onChange={(e) => {
              setValue(e.target.value);
            }}
            style={{ border: "2px solid green" }}
            className="outline-none w-[40vw] p-1.5 pl-3 rounded-2xl text-2xl"
            type="text"
            placeholder="Scan port :- 192.111.123...."
          />
          <button
            onClick={() => {
              if (!trace) {
                cancel_req();
              } else {
                sendRequest();
              }
            }}
            className="cursor-pointer"
          >
            {trace ? <IoMdSearch size={35} /> : "cancel"}
          </button>
        </div>
        <div ref={refer} style={{ display: "none" }} className="loader"></div>
        {
          <span
            style={{ color: "red", opacity: 0.6 }}
            className="text-2xl text-red-500"
          ></span>
        }
      </div>
      <span style={{ color: "red" }} className="text-2xl">
        {msg}
      </span>
      <div
        style={{
          border: "2px solid green",
          marginTop: "20px",
          padding: "0px 100px",
        }}
        className="w-1/2 flex flex-col gap-2 p-3"
      >
        {/* result */}
        <span className="text-2xl">Result</span>
        {Array.isArray(data) ? (
          data.map((val, index) => {
            return (
              <div
                key={index}
                style={{ fontSize: "110%" }}
                className="flex gap-2"
              >
                <span>{val.host}</span>
                <span>{val.port}</span>
                <span>{val.status}</span>
                <span>{val.service}</span>
              </div>
            );
          })
        ) : (
          <div style={{ fontSize: "110%" }} className="flex gap-2">
            <span>{data.host}</span>
            <span>{data.port}</span>
            <span>{data.status}</span>
            <span>{data.service}</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default PortScan;
